### ISSUE TITLE
Template evaluation ignores environment variables

### ISSUE THREAD

**Issue by yjpa7145** [developmentseed/kes#31]
The .env file is loaded at https://github.com/developmentseed/kes/blob/aed4fa98434b9e31c87c514b6d20115eec566bac/src/config.js#L58

On line 268 the Mustache template is passed the values from .env but ignores other values that may be set in the environment.  This should be using `process.env`.

https://github.com/developmentseed/kes/blob/aed4fa98434b9e31c87c514b6d20115eec566bac/src/config.js#L268

**Comment by scisco** [comment]
`loadLocalEnvs` function already loads the environment variables: https://github.com/developmentseed/kes/blob/master/src/utils.js#L65
