### ISSUE TITLE
Kes.uploadCF does not return a Promise in some situations

### ISSUE THREAD

**Issue by yjpa7145** [developmentseed/kes#35]
This function is expected to return a Promise but, under certain circumstances, will just return the value `true`.  At a minimum this should be returning `Promise.resolve(true)`.

https://github.com/developmentseed/kes/blob/aed4fa98434b9e31c87c514b6d20115eec566bac/src/kes.js#L137

**Comment by scisco** [comment]
It returns a promise because of this line: https://github.com/developmentseed/kes/blob/master/src/kes.js#L118
