### ISSUE TITLE
Check for stack existance before trying to create / update

### ISSUE THREAD

**Issue by yjpa7145** [developmentseed/kes#41]
https://github.com/developmentseed/kes/blob/aed4fa98434b9e31c87c514b6d20115eec566bac/src/kes.js#L215

The current code tries to perform a CF create and, if it fails because of the stack already exists, tries to perform an update.  Instead, "describeStacks" should be used to see if the stack exists before trying to perform the actual create / update operation.  There are a few reasons this should be fixed.

* For any given stack, the create operation is only going to happen once and then every call after that is going to be an update.  Despite that, we're still trying to perform a create when, most likely, the stack actually does exist.
* The AWS API throttles how many requests of different types you can make.  You can make a lot more read calls like "describeStacks" than you can "createStacks", so refactoring this would keep us away from those limits.
* The logic in the code would be a lot easier to follow if there were a "stackExists()" call instead of requiring the developer to look all the way through the function to find out that we're catching an exception and re-running based on that.

**Comment by scisco** [comment]
implemented in kes 1.1.0
