### ISSUE TITLE
Add support for deleting a stack

### ISSUE THREAD

**Issue by kamicut** [developmentseed/kes#59]
- [x] Add a deleteStack() function to https://github.com/developmentseed/kes/blob/master/src/kes.js
- [x] Add a cli keyword to https://github.com/developmentseed/kes/blob/master/bin/cli.js
- [x] Add 'delete' to the select statement here https://github.com/developmentseed/kes/blob/master/index.js#L95
- [x] Add tests
- [x] Update docs

**Comment by scisco** [comment]
added

**Comment by kamicut** [comment]
cc @geohacker
